services:
    - type: web
      name: arthistory-web

      autoDeploy: true
      branch: main
      buildCommand: npm ci && npm run build
      pullRequestPreviewsEnabled: true
      rootDir: apps/web
      runtime: static
      staticPublishPath: out
