const ALEX_G_ARTIST_ID = "6lcwlkAjBPSKnFBZjjZFJs";
const DUSTER_ARTIST_ID = "5AyEXCtu3xnnsTGCo4RVZh";

const DEFAULT_ARTIST_IDS = [ALEX_G_ARTIST_ID, DUSTER_ARTIST_ID];

export { DEFAULT_ARTIST_IDS };
