name: build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup node 20
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: 20.15.0

            - name: npm ci
              run: npm ci

            - name: npm run build
              run: npm run build

    release:
        name: semantic-release
        runs-on: ubuntu-latest
        needs: [build]
        if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - uses: actions/checkout@v4

            - name: Setup node 20
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: 20.15.0

            - name: Install semantic-release
              run: npm i -g semantic-release

            - name: Release
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              run: npx semantic-release


